backend:
  name: git-gateway

media_folder: content/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    slug: '{{fields.path}}'
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime, timeFormat: false, format: DD/MM/YYYY }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: tags, label: Tags, widget: "list", allow_add: true, default: [] }
